[project]
name = "gridsync-dep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gridsync>=0.4.3",
    "ipdb>=0.13.13",
    "pytest>=8.3.5",
    "pytest-twisted>=1.14.3",
    "python-decouple>=3.8",
]
